export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_DATA_INITATED = "FETCH_USER_DATA_INITATED";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILED = "FETCH_USER_DATA_FAILED";
